apiVersion: apps/v1
kind: Deployment
metadata:
  name: veidemann-warcvalidator
  labels:
    app.kubernetes.io/name: veidemann-warcvalidator
    app.kubernetes.io/component: warcvalidator
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: veidemann-warcvalidator
      app.kubernetes.io/component: warcvalidator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: veidemann-warcvalidator
        app.kubernetes.io/component: warcvalidator
    spec:
      volumes:
        - name: warcs
          emptyDir: {}
        - name: validwarcs
          emptyDir: {}
        - name: invalidwarcs
          emptyDir: {}
        - name: veidemann-config
          configMap:
            name: veidemann
            items:
              - key: log4j2.xml
                path: log4j2.xml
      containers:
        - name: veidemann-warcvalidator
          image: norsknettarkiv/veidemann-warcvalidator:0.3.1
          volumeMounts:
            - name: warcs
              mountPath: /warcs
            - name: validwarcs
              mountPath: /validwarcs
            - name: invalidwarcs
              mountPath: /invalidwarcs
            - name: veidemann-config
              mountPath: /app/resources/log4j2.xml
              subPath: log4j2.xml
          env:
            - name: SLEEP_TIME
              value: "5"
